### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by xiaonewbee** [byrnexu/betterquant2#1]
您好，很荣幸能阅读这么优秀的框架。
我请教一个问题，这里应该是堆内存分配空间吧，作者这样为什么不用栈分配或内存池。性能会受损吧。
```cpp
struct RawMD {
  RawMD(MsgType msgType, const void* data, std::uint32_t dataLen, bool isLast,
        std::uint64_t localTs = GetTotalUSSince1970()) {
    msgType_ = msgType;
    localTs_ = localTs;

    dataLen_ = dataLen;
    data_ = malloc(dataLen);
    memcpy(data_, data, dataLen_);
```

**Comment by walter211** [comment]
> 我请教一个问题，这里应该是堆内存分配空间吧，作者这样为什么不用栈分配或内存池。性能会受损吧。
> 
> ```c++
> struct RawMD {
>   RawMD(MsgType msgType, const void* data, std::uint32_t dataLen, bool isLast,
>         std::uint64_t localTs = GetTotalUSSince1970()) {
>     msgType_ = msgType;
>     localTs_ = localTs;
> 
>     dataLen_ = dataLen;
>     data_ = malloc(dataLen);
>     memcpy(data_, data, dataLen_);
> ```
在这段代码中，使用堆内存分配空间是为了避免栈溢出的问题。栈内存有限，如果分配的空间过大，可能会导致栈溢出。而使用堆内存可以动态地申请所需的内存空间，不受栈大小的限制。

此外，使用堆内存还可以更好地管理内存资源。当不再需要这个内存时，可以通过调用delete释放该内存，避免内存泄漏。

对于性能方面的影响，堆内存分配可能会比栈内存分配稍慢一些，因为需要系统分配额外的内存空间，并且在释放内存时也需要额外的操作。但是，在实际应用中，这种差异通常可以忽略不计，并且使用动态内存分配可以提供更灵活的内存管理方式。

**Comment by xiaonewbee** [comment]
谢谢解答！
